package dndbuilder.dnd

enum SpellSchool(val label: String):
  case Abjuration    extends SpellSchool("Abjuration")
  case Conjuration   extends SpellSchool("Conjuration")
  case Divination    extends SpellSchool("Divination")
  case Enchantment   extends SpellSchool("Enchantment")
  case Evocation     extends SpellSchool("Evocation")
  case Illusion      extends SpellSchool("Illusion")
  case Necromancy    extends SpellSchool("Necromancy")
  case Transmutation extends SpellSchool("Transmutation")

final case class Spell(
    name: String,
    level: Int,
    school: SpellSchool,
    classes: Set[String],
    ritual: Boolean):

  def isCantrip: Boolean = level == 0

  def levelLabel: String =
    if level == 0 then "Cantrip" else s"Level $level"

  def availableToClass(dndClass: DndClass): Boolean =
    classes.contains(dndClass.name)

object Spell:

  import SpellSchool.*

  val all: List[Spell] = List(
    Spell("Acid Splash", 0, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Chill Touch", 0, Necromancy, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Dancing Lights", 0, Illusion, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Druidcraft", 0, Transmutation, Set("Druid"), false),
    Spell("Eldritch Blast", 0, Evocation, Set("Warlock"), false),
    Spell("Elementalism", 0, Transmutation, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Fire Bolt", 0, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Guidance", 0, Divination, Set("Cleric", "Druid"), false),
    Spell("Light", 0, Evocation, Set("Bard", "Cleric", "Sorcerer", "Wizard"), false),
    Spell("Mage Hand", 0, Conjuration, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Mending", 0, Transmutation, Set("Bard", "Cleric", "Druid", "Sorcerer", "Wizard"), false),
    Spell("Message", 0, Transmutation, Set("Bard", "Druid", "Sorcerer", "Wizard"), false),
    Spell("Minor Illusion", 0, Illusion, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Poison Spray", 0, Necromancy, Set("Druid", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Prestidigitation", 0, Transmutation, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Produce Flame", 0, Conjuration, Set("Druid"), false),
    Spell("Ray of Frost", 0, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Resistance", 0, Abjuration, Set("Cleric", "Druid"), false),
    Spell("Sacred Flame", 0, Evocation, Set("Cleric"), false),
    Spell("Shillelagh", 0, Transmutation, Set("Druid"), false),
    Spell("Shocking Grasp", 0, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Sorcerous Burst", 0, Evocation, Set("Sorcerer"), false),
    Spell("Spare the Dying", 0, Necromancy, Set("Cleric", "Druid"), false),
    Spell("Starry Wisp", 0, Evocation, Set("Bard", "Druid"), false),
    Spell("Thaumaturgy", 0, Transmutation, Set("Cleric"), false),
    Spell("True Strike", 0, Divination, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Vicious Mockery", 0, Enchantment, Set("Bard"), false),
    Spell("Alarm", 1, Abjuration, Set("Ranger", "Wizard"), true),
    Spell("Animal Friendship", 1, Enchantment, Set("Bard", "Druid", "Ranger"), false),
    Spell("Bane", 1, Enchantment, Set("Bard", "Cleric", "Warlock"), false),
    Spell("Bless", 1, Enchantment, Set("Cleric", "Paladin"), false),
    Spell("Burning Hands", 1, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Charm Person", 1, Enchantment, Set("Bard", "Druid", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Chromatic Orb", 1, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Color Spray", 1, Illusion, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Command", 1, Enchantment, Set("Bard", "Cleric", "Paladin"), false),
    Spell("Comprehend Languages", 1, Divination, Set("Bard", "Sorcerer", "Warlock", "Wizard"), true),
    Spell("Create or Destroy Water", 1, Transmutation, Set("Cleric", "Druid"), false),
    Spell("Cure Wounds", 1, Abjuration, Set("Bard", "Cleric", "Druid", "Paladin", "Ranger"), false),
    Spell("Detect Evil and Good", 1, Divination, Set("Cleric", "Paladin"), false),
    Spell("Detect Magic", 1, Divination, Set("Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Warlock", "Wizard"), true),
    Spell("Detect Poison and Disease", 1, Divination, Set("Cleric", "Druid", "Paladin", "Ranger"), true),
    Spell("Disguise Self", 1, Illusion, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Dissonant Whispers", 1, Enchantment, Set("Bard"), false),
    Spell("Divine Favor", 1, Transmutation, Set("Paladin"), false),
    Spell("Divine Smite", 1, Evocation, Set("Paladin"), false),
    Spell("Ensnaring Strike", 1, Conjuration, Set("Ranger"), false),
    Spell("Entangle", 1, Conjuration, Set("Druid", "Ranger"), false),
    Spell("Expeditious Retreat", 1, Transmutation, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Faerie Fire", 1, Evocation, Set("Bard", "Druid"), false),
    Spell("False Life", 1, Necromancy, Set("Sorcerer", "Wizard"), false),
    Spell("Feather Fall", 1, Transmutation, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Find Familiar", 1, Conjuration, Set("Wizard"), true),
    Spell("Floating Disk", 1, Conjuration, Set("Wizard"), true),
    Spell("Fog Cloud", 1, Conjuration, Set("Druid", "Ranger", "Sorcerer", "Wizard"), false),
    Spell("Goodberry", 1, Conjuration, Set("Druid", "Ranger"), false),
    Spell("Grease", 1, Conjuration, Set("Sorcerer", "Wizard"), false),
    Spell("Guiding Bolt", 1, Evocation, Set("Cleric"), false),
    Spell("Healing Word", 1, Abjuration, Set("Bard", "Cleric", "Druid"), false),
    Spell("Hellish Rebuke", 1, Evocation, Set("Warlock"), false),
    Spell("Heroism", 1, Enchantment, Set("Bard", "Paladin"), false),
    Spell("Hex", 1, Enchantment, Set("Warlock"), false),
    Spell("Hideous Laughter", 1, Enchantment, Set("Bard", "Warlock", "Wizard"), false),
    Spell("Hunter's Mark", 1, Divination, Set("Ranger"), false),
    Spell("Ice Knife", 1, Conjuration, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Identify", 1, Divination, Set("Bard", "Wizard"), true),
    Spell("Illusory Script", 1, Illusion, Set("Bard", "Warlock", "Wizard"), true),
    Spell("Inflict Wounds", 1, Necromancy, Set("Cleric"), false),
    Spell("Jump", 1, Transmutation, Set("Druid", "Ranger", "Sorcerer", "Wizard"), false),
    Spell("Longstrider", 1, Transmutation, Set("Bard", "Druid", "Ranger", "Wizard"), false),
    Spell("Mage Armor", 1, Abjuration, Set("Sorcerer", "Wizard"), false),
    Spell("Magic Missile", 1, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Protection from Evil and Good", 1, Abjuration, Set("Cleric", "Druid", "Paladin", "Warlock", "Wizard"), false),
    Spell("Purify Food and Drink", 1, Transmutation, Set("Cleric", "Druid", "Paladin"), true),
    Spell("Ray of Sickness", 1, Necromancy, Set("Sorcerer", "Wizard"), false),
    Spell("Sanctuary", 1, Abjuration, Set("Cleric"), false),
    Spell("Searing Smite", 1, Evocation, Set("Paladin"), false),
    Spell("Shield", 1, Abjuration, Set("Sorcerer", "Wizard"), false),
    Spell("Shield of Faith", 1, Abjuration, Set("Cleric", "Paladin"), false),
    Spell("Silent Image", 1, Illusion, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Sleep", 1, Enchantment, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Speak with Animals", 1, Divination, Set("Bard", "Druid", "Ranger", "Warlock"), true),
    Spell("Thunderwave", 1, Evocation, Set("Bard", "Druid", "Sorcerer", "Wizard"), false),
    Spell("Unseen Servant", 1, Conjuration, Set("Bard", "Warlock", "Wizard"), true),
    Spell("Acid Arrow", 2, Evocation, Set("Wizard"), false),
    Spell("Aid", 2, Abjuration, Set("Bard", "Cleric", "Druid", "Paladin", "Ranger"), false),
    Spell("Alter Self", 2, Transmutation, Set("Sorcerer", "Wizard"), false),
    Spell("Animal Messenger", 2, Enchantment, Set("Bard", "Druid", "Ranger"), true),
    Spell("Arcane Lock", 2, Abjuration, Set("Wizard"), false),
    Spell("Arcanist's Magic Aura", 2, Illusion, Set("Wizard"), false),
    Spell("Augury", 2, Divination, Set("Cleric", "Druid", "Wizard"), true),
    Spell("Barkskin", 2, Transmutation, Set("Druid", "Ranger"), false),
    Spell("Blindness/Deafness", 2, Transmutation, Set("Bard", "Cleric", "Sorcerer", "Wizard"), false),
    Spell("Calm Emotions", 2, Enchantment, Set("Bard", "Cleric"), false),
    Spell("Continual Flame", 2, Evocation, Set("Cleric", "Druid", "Wizard"), false),
    Spell("Darkness", 2, Evocation, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Darkvision", 2, Transmutation, Set("Druid", "Ranger", "Sorcerer", "Wizard"), false),
    Spell("Detect Thoughts", 2, Divination, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Dragon's Breath", 2, Transmutation, Set("Sorcerer", "Wizard"), false),
    Spell("Enhance Ability", 2, Transmutation, Set("Bard", "Cleric", "Druid", "Ranger", "Sorcerer", "Wizard"), false),
    Spell("Enlarge/Reduce", 2, Transmutation, Set("Bard", "Druid", "Sorcerer", "Wizard"), false),
    Spell("Enthrall", 2, Enchantment, Set("Bard", "Warlock"), false),
    Spell("Find Steed", 2, Conjuration, Set("Paladin"), false),
    Spell("Find Traps", 2, Divination, Set("Cleric", "Druid", "Ranger"), false),
    Spell("Flame Blade", 2, Evocation, Set("Druid", "Sorcerer"), false),
    Spell("Flaming Sphere", 2, Conjuration, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Gentle Repose", 2, Necromancy, Set("Cleric", "Paladin", "Wizard"), true),
    Spell("Gust of Wind", 2, Evocation, Set("Druid", "Ranger", "Sorcerer", "Wizard"), false),
    Spell("Heat Metal", 2, Transmutation, Set("Bard", "Druid"), false),
    Spell("Hold Person", 2, Enchantment, Set("Bard", "Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Invisibility", 2, Illusion, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Knock", 2, Transmutation, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Lesser Restoration", 2, Abjuration, Set("Bard", "Cleric", "Druid", "Paladin", "Ranger"), false),
    Spell("Levitate", 2, Transmutation, Set("Sorcerer", "Wizard"), false),
    Spell("Locate Animals or Plants", 2, Divination, Set("Bard", "Druid", "Ranger"), true),
    Spell("Locate Object", 2, Divination, Set("Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"), false),
    Spell("Magic Mouth", 2, Illusion, Set("Bard", "Wizard"), true),
    Spell("Magic Weapon", 2, Transmutation, Set("Paladin", "Ranger", "Sorcerer", "Wizard"), false),
    Spell("Mind Spike", 2, Divination, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Mirror Image", 2, Illusion, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Misty Step", 2, Conjuration, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Moonbeam", 2, Evocation, Set("Druid"), false),
    Spell("Pass without Trace", 2, Abjuration, Set("Druid", "Ranger"), false),
    Spell("Phantasmal Force", 2, Illusion, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Prayer of Healing", 2, Abjuration, Set("Cleric", "Paladin"), false),
    Spell("Protection from Poison", 2, Abjuration, Set("Cleric", "Druid", "Paladin", "Ranger"), false),
    Spell("Rope Trick", 2, Transmutation, Set("Wizard"), false),
    Spell("Scorching Ray", 2, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("See Invisibility", 2, Divination, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Shatter", 2, Evocation, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Shining Smite", 2, Transmutation, Set("Paladin"), false),
    Spell("Silence", 2, Illusion, Set("Bard", "Cleric", "Ranger"), true),
    Spell("Spider Climb", 2, Transmutation, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Spike Growth", 2, Transmutation, Set("Druid", "Ranger"), false),
    Spell("Spiritual Weapon", 2, Evocation, Set("Cleric"), false),
    Spell("Suggestion", 2, Enchantment, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Warding Bond", 2, Abjuration, Set("Cleric", "Paladin"), false),
    Spell("Web", 2, Conjuration, Set("Sorcerer", "Wizard"), false),
    Spell("Zone of Truth", 2, Enchantment, Set("Bard", "Cleric", "Paladin"), false),
    Spell("Animate Dead", 3, Necromancy, Set("Cleric", "Wizard"), false),
    Spell("Beacon of Hope", 3, Abjuration, Set("Cleric"), false),
    Spell("Bestow Curse", 3, Necromancy, Set("Bard", "Cleric", "Wizard"), false),
    Spell("Blink", 3, Transmutation, Set("Sorcerer", "Wizard"), false),
    Spell("Call Lightning", 3, Conjuration, Set("Druid"), false),
    Spell("Clairvoyance", 3, Divination, Set("Bard", "Cleric", "Sorcerer", "Wizard"), false),
    Spell("Conjure Animals", 3, Conjuration, Set("Druid", "Ranger"), false),
    Spell("Counterspell", 3, Abjuration, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Create Food and Water", 3, Conjuration, Set("Cleric", "Paladin"), false),
    Spell("Daylight", 3, Evocation, Set("Cleric", "Druid", "Paladin", "Ranger", "Sorcerer"), false),
    Spell("Dispel Magic", 3, Abjuration, Set("Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Fear", 3, Illusion, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Fireball", 3, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Fly", 3, Transmutation, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Gaseous Form", 3, Transmutation, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Glyph of Warding", 3, Abjuration, Set("Bard", "Cleric", "Wizard"), false),
    Spell("Haste", 3, Transmutation, Set("Sorcerer", "Wizard"), false),
    Spell("Hypnotic Pattern", 3, Illusion, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Lightning Bolt", 3, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Magic Circle", 3, Abjuration, Set("Cleric", "Paladin", "Warlock", "Wizard"), false),
    Spell("Major Image", 3, Illusion, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Meld into Stone", 3, Transmutation, Set("Cleric", "Druid", "Ranger"), true),
    Spell("Nondetection", 3, Abjuration, Set("Bard", "Ranger", "Wizard"), false),
    Spell("Phantom Steed", 3, Illusion, Set("Wizard"), true),
    Spell("Plant Growth", 3, Transmutation, Set("Bard", "Druid", "Ranger"), false),
    Spell("Protection from Energy", 3, Abjuration, Set("Cleric", "Druid", "Ranger", "Sorcerer", "Wizard"), false),
    Spell("Remove Curse", 3, Abjuration, Set("Cleric", "Paladin", "Warlock", "Wizard"), false),
    Spell("Revivify", 3, Necromancy, Set("Cleric", "Druid", "Paladin", "Ranger"), false),
    Spell("Sending", 3, Divination, Set("Bard", "Cleric", "Wizard"), false),
    Spell("Sleet Storm", 3, Conjuration, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Slow", 3, Transmutation, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Speak with Dead", 3, Necromancy, Set("Bard", "Cleric", "Wizard"), false),
    Spell("Speak with Plants", 3, Transmutation, Set("Bard", "Druid", "Ranger"), false),
    Spell("Spirit Guardians", 3, Conjuration, Set("Cleric"), false),
    Spell("Stinking Cloud", 3, Conjuration, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Tiny Hut", 3, Evocation, Set("Bard", "Wizard"), true),
    Spell("Tongues", 3, Divination, Set("Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Vampiric Touch", 3, Necromancy, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Water Breathing", 3, Transmutation, Set("Druid", "Ranger", "Sorcerer", "Wizard"), true),
    Spell("Water Walk", 3, Transmutation, Set("Cleric", "Druid", "Ranger", "Sorcerer"), true),
    Spell("Wind Wall", 3, Evocation, Set("Druid", "Ranger"), false),
    Spell("Arcane Eye", 4, Divination, Set("Wizard"), false),
    Spell("Aura of Life", 4, Abjuration, Set("Cleric", "Paladin"), false),
    Spell("Banishment", 4, Abjuration, Set("Cleric", "Paladin", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Black Tentacles", 4, Conjuration, Set("Wizard"), false),
    Spell("Blight", 4, Necromancy, Set("Druid", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Charm Monster", 4, Enchantment, Set("Bard", "Druid", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Compulsion", 4, Enchantment, Set("Bard"), false),
    Spell("Confusion", 4, Enchantment, Set("Bard", "Druid", "Sorcerer", "Wizard"), false),
    Spell("Conjure Minor Elementals", 4, Conjuration, Set("Druid", "Wizard"), false),
    Spell("Conjure Woodland Beings", 4, Conjuration, Set("Druid", "Ranger"), false),
    Spell("Control Water", 4, Transmutation, Set("Cleric", "Druid", "Wizard"), false),
    Spell("Death Ward", 4, Abjuration, Set("Cleric", "Paladin"), false),
    Spell("Dimension Door", 4, Conjuration, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Divination", 4, Divination, Set("Cleric", "Druid", "Wizard"), true),
    Spell("Dominate Beast", 4, Enchantment, Set("Druid", "Ranger", "Sorcerer"), false),
    Spell("Fabricate", 4, Transmutation, Set("Wizard"), false),
    Spell("Faithful Hound", 4, Conjuration, Set("Wizard"), false),
    Spell("Fire Shield", 4, Evocation, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Freedom of Movement", 4, Abjuration, Set("Bard", "Cleric", "Druid", "Ranger"), false),
    Spell("Giant Insect", 4, Conjuration, Set("Druid"), false),
    Spell("Greater Invisibility", 4, Illusion, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Hallucinatory Terrain", 4, Illusion, Set("Bard", "Druid", "Warlock", "Wizard"), false),
    Spell("Ice Storm", 4, Evocation, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Locate Creature", 4, Divination, Set("Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"), false),
    Spell("Phantasmal Killer", 4, Illusion, Set("Bard", "Wizard"), false),
    Spell("Polymorph", 4, Transmutation, Set("Bard", "Druid", "Sorcerer", "Wizard"), false),
    Spell("Private Sanctum", 4, Abjuration, Set("Wizard"), false),
    Spell("Resilient Sphere", 4, Abjuration, Set("Wizard"), false),
    Spell("Secret Chest", 4, Conjuration, Set("Wizard"), false),
    Spell("Stone Shape", 4, Transmutation, Set("Cleric", "Druid", "Wizard"), false),
    Spell("Stoneskin", 4, Transmutation, Set("Druid", "Ranger", "Sorcerer", "Wizard"), false),
    Spell("Vitriolic Sphere", 4, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Wall of Fire", 4, Evocation, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Animate Objects", 5, Transmutation, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Antilife Shell", 5, Abjuration, Set("Druid"), false),
    Spell("Arcane Hand", 5, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Awaken", 5, Transmutation, Set("Bard", "Druid"), false),
    Spell("Cloudkill", 5, Conjuration, Set("Sorcerer", "Wizard"), false),
    Spell("Commune", 5, Divination, Set("Cleric"), true),
    Spell("Commune with Nature", 5, Divination, Set("Druid", "Ranger"), true),
    Spell("Cone of Cold", 5, Evocation, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Conjure Elemental", 5, Conjuration, Set("Druid", "Wizard"), false),
    Spell("Contact Other Plane", 5, Divination, Set("Warlock", "Wizard"), true),
    Spell("Contagion", 5, Necromancy, Set("Cleric", "Druid"), false),
    Spell("Creation", 5, Illusion, Set("Sorcerer", "Wizard"), false),
    Spell("Dispel Evil and Good", 5, Abjuration, Set("Cleric", "Paladin"), false),
    Spell("Dominate Person", 5, Enchantment, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Dream", 5, Illusion, Set("Bard", "Warlock", "Wizard"), false),
    Spell("Flame Strike", 5, Evocation, Set("Cleric"), false),
    Spell("Geas", 5, Enchantment, Set("Bard", "Cleric", "Druid", "Paladin", "Wizard"), false),
    Spell("Greater Restoration", 5, Abjuration, Set("Bard", "Cleric", "Druid", "Paladin", "Ranger"), false),
    Spell("Hallow", 5, Abjuration, Set("Cleric"), false),
    Spell("Hold Monster", 5, Enchantment, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Insect Plague", 5, Conjuration, Set("Cleric", "Druid", "Sorcerer"), false),
    Spell("Legend Lore", 5, Divination, Set("Bard", "Cleric", "Wizard"), false),
    Spell("Mass Cure Wounds", 5, Abjuration, Set("Bard", "Cleric", "Druid"), false),
    Spell("Mass Healing Word", 5, Abjuration, Set("Bard", "Cleric"), false),
    Spell("Mislead", 5, Illusion, Set("Bard", "Warlock", "Wizard"), false),
    Spell("Modify Memory", 5, Enchantment, Set("Bard", "Wizard"), false),
    Spell("Passwall", 5, Transmutation, Set("Wizard"), false),
    Spell("Planar Binding", 5, Abjuration, Set("Bard", "Cleric", "Druid", "Warlock", "Wizard"), false),
    Spell("Raise Dead", 5, Necromancy, Set("Bard", "Cleric", "Paladin"), false),
    Spell("Reincarnate", 5, Necromancy, Set("Druid"), false),
    Spell("Scrying", 5, Divination, Set("Bard", "Cleric", "Druid", "Warlock", "Wizard"), false),
    Spell("Seeming", 5, Illusion, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Summon Dragon", 5, Conjuration, Set("Wizard"), false),
    Spell("Telekinesis", 5, Transmutation, Set("Sorcerer", "Wizard"), false),
    Spell("Telepathic Bond", 5, Divination, Set("Bard", "Wizard"), true),
    Spell("Teleportation Circle", 5, Conjuration, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Tree Stride", 5, Conjuration, Set("Druid", "Ranger"), false),
    Spell("Wall of Force", 5, Evocation, Set("Wizard"), false),
    Spell("Wall of Stone", 5, Evocation, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Blade Barrier", 6, Evocation, Set("Cleric"), false),
    Spell("Chain Lightning", 6, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Circle of Death", 6, Necromancy, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Conjure Fey", 6, Conjuration, Set("Druid"), false),
    Spell("Contingency", 6, Abjuration, Set("Wizard"), false),
    Spell("Create Undead", 6, Necromancy, Set("Cleric", "Warlock", "Wizard"), false),
    Spell("Disintegrate", 6, Transmutation, Set("Sorcerer", "Wizard"), false),
    Spell("Eyebite", 6, Necromancy, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Find the Path", 6, Divination, Set("Bard", "Cleric", "Druid"), false),
    Spell("Flesh to Stone", 6, Transmutation, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Forbiddance", 6, Abjuration, Set("Cleric"), true),
    Spell("Freezing Sphere", 6, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Globe of Invulnerability", 6, Abjuration, Set("Sorcerer", "Wizard"), false),
    Spell("Guards and Wards", 6, Abjuration, Set("Bard", "Wizard"), false),
    Spell("Harm", 6, Necromancy, Set("Cleric"), false),
    Spell("Heal", 6, Abjuration, Set("Cleric", "Druid"), false),
    Spell("Heroes' Feast", 6, Conjuration, Set("Bard", "Cleric", "Druid"), false),
    Spell("Instant Summons", 6, Conjuration, Set("Wizard"), true),
    Spell("Irresistible Dance", 6, Enchantment, Set("Bard", "Wizard"), false),
    Spell("Magic Jar", 6, Necromancy, Set("Wizard"), false),
    Spell("Mass Suggestion", 6, Enchantment, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Move Earth", 6, Transmutation, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Planar Ally", 6, Conjuration, Set("Cleric"), false),
    Spell("Programmed Illusion", 6, Illusion, Set("Bard", "Wizard"), false),
    Spell("Sunbeam", 6, Evocation, Set("Cleric", "Druid", "Sorcerer", "Wizard"), false),
    Spell("Transport via Plants", 6, Conjuration, Set("Druid"), false),
    Spell("True Seeing", 6, Divination, Set("Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Wall of Ice", 6, Evocation, Set("Wizard"), false),
    Spell("Wall of Thorns", 6, Conjuration, Set("Druid"), false),
    Spell("Wind Walk", 6, Transmutation, Set("Druid"), false),
    Spell("Word of Recall", 6, Conjuration, Set("Cleric"), false),
    Spell("Arcane Sword", 7, Evocation, Set("Bard", "Wizard"), false),
    Spell("Conjure Celestial", 7, Conjuration, Set("Cleric"), false),
    Spell("Delayed Blast Fireball", 7, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Divine Word", 7, Evocation, Set("Cleric"), false),
    Spell("Etherealness", 7, Conjuration, Set("Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Finger of Death", 7, Necromancy, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Fire Storm", 7, Evocation, Set("Cleric", "Druid", "Sorcerer"), false),
    Spell("Forcecage", 7, Evocation, Set("Bard", "Warlock", "Wizard"), false),
    Spell("Magnificent Mansion", 7, Conjuration, Set("Bard", "Wizard"), false),
    Spell("Mirage Arcane", 7, Illusion, Set("Bard", "Druid", "Wizard"), false),
    Spell("Plane Shift", 7, Conjuration, Set("Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Prismatic Spray", 7, Evocation, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Project Image", 7, Illusion, Set("Bard", "Wizard"), false),
    Spell("Regenerate", 7, Transmutation, Set("Bard", "Cleric", "Druid"), false),
    Spell("Resurrection", 7, Necromancy, Set("Bard", "Cleric"), false),
    Spell("Reverse Gravity", 7, Transmutation, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Sequester", 7, Transmutation, Set("Wizard"), false),
    Spell("Simulacrum", 7, Illusion, Set("Wizard"), false),
    Spell("Symbol", 7, Abjuration, Set("Bard", "Cleric", "Druid", "Wizard"), false),
    Spell("Teleport", 7, Conjuration, Set("Bard", "Sorcerer", "Wizard"), false),
    Spell("Animal Shapes", 8, Transmutation, Set("Druid"), false),
    Spell("Antimagic Field", 8, Abjuration, Set("Cleric", "Wizard"), false),
    Spell("Antipathy/Sympathy", 8, Enchantment, Set("Bard", "Druid", "Wizard"), false),
    Spell("Befuddlement", 8, Enchantment, Set("Bard", "Druid", "Warlock", "Wizard"), false),
    Spell("Clone", 8, Necromancy, Set("Wizard"), false),
    Spell("Control Weather", 8, Transmutation, Set("Cleric", "Druid", "Wizard"), false),
    Spell("Demiplane", 8, Conjuration, Set("Sorcerer", "Warlock", "Wizard"), false),
    Spell("Dominate Monster", 8, Enchantment, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Earthquake", 8, Transmutation, Set("Cleric", "Druid", "Sorcerer"), false),
    Spell("Glibness", 8, Enchantment, Set("Bard", "Warlock"), false),
    Spell("Holy Aura", 8, Abjuration, Set("Cleric"), false),
    Spell("Incendiary Cloud", 8, Conjuration, Set("Druid", "Sorcerer", "Wizard"), false),
    Spell("Maze", 8, Conjuration, Set("Wizard"), false),
    Spell("Mind Blank", 8, Abjuration, Set("Bard", "Wizard"), false),
    Spell("Power Word Stun", 8, Enchantment, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Sunburst", 8, Evocation, Set("Cleric", "Druid", "Sorcerer", "Wizard"), false),
    Spell("Tsunami", 8, Conjuration, Set("Druid"), false),
    Spell("Astral Projection", 9, Necromancy, Set("Cleric", "Warlock", "Wizard"), false),
    Spell("Foresight", 9, Divination, Set("Bard", "Druid", "Warlock", "Wizard"), false),
    Spell("Gate", 9, Conjuration, Set("Cleric", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Imprisonment", 9, Abjuration, Set("Warlock", "Wizard"), false),
    Spell("Mass Heal", 9, Abjuration, Set("Cleric"), false),
    Spell("Meteor Swarm", 9, Evocation, Set("Sorcerer", "Wizard"), false),
    Spell("Power Word Heal", 9, Enchantment, Set("Bard", "Cleric"), false),
    Spell("Power Word Kill", 9, Enchantment, Set("Bard", "Sorcerer", "Warlock", "Wizard"), false),
    Spell("Prismatic Wall", 9, Abjuration, Set("Bard", "Wizard"), false),
    Spell("Shapechange", 9, Transmutation, Set("Druid", "Wizard"), false),
    Spell("Storm of Vengeance", 9, Conjuration, Set("Druid"), false),
    Spell("Time Stop", 9, Transmutation, Set("Sorcerer", "Wizard"), false),
    Spell("True Polymorph", 9, Transmutation, Set("Bard", "Warlock", "Wizard"), false),
    Spell("True Resurrection", 9, Necromancy, Set("Cleric", "Druid"), false),
    Spell("Weird", 9, Illusion, Set("Warlock", "Wizard"), false),
    Spell("Wish", 9, Conjuration, Set("Sorcerer", "Wizard"), false)
  )

  val byName: Map[String, Spell] = all.map(s => s.name -> s).toMap

  def forClass(dndClass: DndClass, spellLevel: Int): List[Spell] =
    all.filter(s => s.level == spellLevel && s.availableToClass(dndClass))

  def cantripsForClass(dndClass: DndClass): List[Spell] =
    forClass(dndClass, 0)

  def level1ForClass(dndClass: DndClass): List[Spell] =
    forClass(dndClass, 1)
